### ISSUE TITLE
Zlib.crc32 calculates CRC checksum for string and initial CRC value FAILED

### ISSUE THREAD

**Issue by voxik** [ruby/spec#932] opened 2022-06-30 09:19 UTC
Today for the first time, the Ruby build on Fedora [failed](https://koschei.fedoraproject.org/build/13150895) with the following error

~~~
1)
Zlib.crc32 calculates CRC checksum for string and initial CRC value FAILED
Expected 72057589981397915 == 4046865307
to be truthy but was false
/builddir/build/BUILD/ruby-3.1.2/spec/ruby/library/zlib/crc32_spec.rb:27:in `block (2 levels) in <top (required)>'
/builddir/build/BUILD/ruby-3.1.2/spec/ruby/library/zlib/crc32_spec.rb:4:in `<top (required)>'
~~~

It seems that one of the changes is the zlib update from 1.2.11-31.fc36 to 1.2.12-1.fc37.

The same issue can be seen in Ruby CI:

https://rubyci.org/logs/rubyci.s3.amazonaws.com/funtoo/ruby-2.7/log/20220427T080138Z.diff.html.gz

and the diff also indicates change from zlib 1.2.11 to 1.2.12. So it seems the test should be probably somehow adapted, unless there is bug in zlib 1.2.12.

**Comment by ljavorsk** [comment] 2022-06-30 13:47
I apologize for this problem. I made a pretty big zlib rebase yesterday and I should've provided it in the private copr repository for deeper testing.

I've asked the Fedora Releng team to untag this build, so it should be fine again.

I'll fix the new release and provide the repository for testing purposes when it's ready

**Comment by mscastanho** [comment] 2022-06-30 14:05
This could be related the issue fixed by [this zlib commit](https://github.com/madler/zlib/commit/ec3df00224d4b396e2ac6586ab5d25f673caa4c2).

**Comment by eregon** [comment] 2022-07-05 11:47
Let's close, it seems an incompatibility/bug from zlib, which sounds like it will get fixed to be the same as before.

FWIW I know of 1 ABI issue with zlib in
https://github.com/ruby/spec/blob/ab32a1a4d737595a6193682728c8d510e135c99e/library/zlib/crc_table_spec.rb#L4-L11
But that sounds fair enough given get_crc_table() is an "undocumented function".

**Closed by eregon** 2022-07-05 11:47 UTC

**Comment by ljavorsk** [comment] 2022-07-07 09:35
The Fedora zlib RPMs with the commit above applied are available for testing, could you please test them and let me know if the issue is fixed?

You can download them here: https://ljavorsk.fedorapeople.org/zlib/

**Comment by voxik** [comment] 2022-07-07 18:15
@pvalena, @junaruga, @jackorp could you please help me and try the updated zlib and see if it resolves the issue above?

**Comment by jackorp** [comment] 2022-07-07 18:49
> could you please help me and try the updated zlib and see if it resolves the issue above?

I am taking a look using the RPMs from @ljavorsk's link.

**Comment by ljavorsk** [comment] 2022-07-08 07:56
Okay, please let me know as soon as you can if I can push this release to Fedora Rawhide.

The releng team is pinging me for having this fixed ASAP.

Thank you for the help :)

**Comment by jackorp** [comment] 2022-07-08 08:32
The failure is not zlib related, as it is related to directory permission manipulation.

This seems like the commit that fixes it: https://github.com/rubygems/rubygems/commit/623162ad2bb3b589bddcc32616492a2bc4651726
